[project]
name = "dezero3-k20ku"
version = "0.1.0"
description = "Running along with Deep Learning from Scratch 3 (O'Reilly Japan, Koki Satito)"
readme = "README.md"
authors = [{ name = "k20ku" }]
license = "MIT"
requires-python = ">=3.12"
dependencies = ["numpy>=2.0, <3.0"]

[project.urls]
Repository = "https://github.com/k20ku/dezero3"

[dependency-groups]
dev = [
    "devtools>=0.12",
    "ipython>=9.8",
    "mypy>=2.1",
    "pytest>=9.0",
    "ruff>=0.15",
]

[build-system]
requires = ["uv_build >= 0.11.7, <0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "dezero"
module-root = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
# https://docs.pytest.org/en/latest/explanation/goodpractices.html#choosing-a-test-layout
addopts = ["--import-mode=importlib"]

[tool.mypy]
# https://dev.to/zim95/chapter-3-using-pytest-mypy-and-flake8-for-testing-30cl
mypy_path = "src"
ignore_missing_imports = true
